TiersMonde/TiersMonde/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('event/', include('event.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TiersMonde/event/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'event'
urlpatterns = [
    path('', views.index, name='index'),
    path('liste', views.liste, name='liste'),
    path('<int:event_id>/detail/', views.detail, name='detail'),
    path('informations/', views.informations, name='informations'),
    path('register/', views.register, name='register'),
    path('registered/', views.registered, name='registered'),
    path('welcome/', views.welcome, name='welcome'),
    path('login/', views.my_login, name='login'),
    path('logout/', views.my_logout, name='logout'),
    path('password/', views.new_password, name='password'),
    path('contact/', views.contact, name='contact'),
    path('<int:event_id>/detail/acheter/', views.acheter, name='acheter'),
    path('faq/', views.faq, name='faq'),
    path('profil/', views.profil, name='profil'),
    path('annuler/<int:event_id>', views.annuler, name='annuler'),
    path('salle/', views.salle, name='salle'),
    # path('<int:event_id>/detail/reserver/', views.reserver, name='reserver'),
]

TiersMonde/event/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

# Create your models here.
class Users(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    avatar_user = models.ImageField(upload_to='avatar', blank=True)
    
    def __str__(self):
        affiche = f"{self.user.last_name} {self.user.first_name}"
        return affiche

class EventType(models.Model):
    name_type = models.CharField(max_length=50)

    def __str__(self):
        return self.name_type

class HallCategory(models.Model):
    hall_category = models.CharField(max_length=50)

    def __str__(self):
        return self.hall_category

class Material(models.Model):
    category_material = models.CharField(max_length=50)

    def __str__(self):
        return self.category_material

class Artist(models.Model):
    name_artist = models.CharField(max_length=50)
    skill_artist = models.CharField(max_length=50)
    pics_artist = models.ImageField(upload_to='picsArtist', blank=True)

    def __str__(self):
        affiche = f"{self.name_artist} {self.skill_artist}"
        return affiche

class Groups(models.Model):
    name_group = models.CharField(max_length=50)
    type_group = models.CharField(max_length=50)
    artist = models.ManyToManyField(Artist , blank=True)
    pics_group = models.ImageField(upload_to='picsArtist', blank=True)

    def __str__(self):
        affiche = f"{self.name_group} {self.type_group}"
        return affiche

class Events(models.Model):
    name_event = models.CharField(max_length=50)
    av_ticket = models.IntegerField(default=0)
    begin_date = models.DateTimeField("Date de debut d'event")
    end_date = models.DateTimeField("Date de fin d'event")
    description_event = models.CharField(max_length=255, null=True, blank=True)
    type = models.ForeignKey(EventType, on_delete=models.CASCADE)
    group = models.ManyToManyField(Groups,blank=True)
    users = models.ManyToManyField(User, through='Achat', blank=True)

    def __str__(self):
        affiche = f" {self.name_event}  {self.av_ticket}"
        return affiche 

    

class Halls(models.Model):
    name_hall = models.CharField(max_length=50)
    size_hall = models.IntegerField(default=0)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    event = models.ForeignKey(Events, on_delete=models.CASCADE)
    hall_category = models.ManyToManyField(HallCategory,blank=True)

    def __str__(self):
        affiche =f" {self.name_hall} {self.size_hall} {self.hall_category}"
        return affiche

class Contact(models.Model):
    users = models.CharField(max_length=50)
    name_contact = models.CharField(max_length=50)
    mail_contact = models.CharField(max_length=50)
    pub_date = models.DateField("Date de publication")

class Achat(models.Model):
    event = models.ForeignKey(Events, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    billets_user = models.IntegerField(default=0)

    def __str__(self):
        affiche =f" {self.billets_user} {self.user}{self.event}"
        return affiche

TiersMonde/event/views.py
from multiprocessing import Event, context
from django.shortcuts import render, get_object_or_404
from . models import Events , Users, Achat
from django.contrib.auth import authenticate, login , logout
from django.contrib.auth.models import User
from django.contrib.auth.models import AnonymousUser


# Create your views here.
def index(request):
    dernier_event = Events.objects.order_by('begin_date')
    context = {'event_list': dernier_event}
    return render(request, 'event/index.html', context)

def detail(request, event_id):
    event = get_object_or_404(Events, pk=event_id)
    return render(request, 'event/detail.html', {'event':event})

def informations(request):
    return render(request, 'event/informations.html')

def my_login(request):
    return render(request, 'event/login.html')

def my_logout(request):
    logout(request)
    return render(request, 'event/logout.html')

def new_password(newpwd):
    newpwd = User.objects.get(username ='new_password')
    newpwd.set_password('new_password')
    newpwd.save()

def register(request):
    return render(request, 'event/register.html')

def registered(request):
    name = request.POST['user_name']
    firstname = request.POST['user_firstname']
    pwd = request.POST['user_pwd']
    email = request.POST['user_email']
    username = firstname[0].lower() + "." + name.lower()     
    user = User.objects.create_user(username, email, pwd)
    utilisateur = Users(user=user)
    user.last_name = name
    user.first_name = firstname
    user.save()
    utilisateur.save()
    context = {'user':user}
    return render(request, 'event/registered.html', context)

def welcome(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    context = {'user':user}
    if user is not None :
        login(request, user)
        return render(request, 'event/welcome.html', context)
    else:
        return render(request, 'event/error_log.html')

def faq(request):
    return render(request, 'event/faq.html')

def contact(request):
    return render(request, 'event/contact.html')

def liste(request):
    dernier_event = Events.objects.order_by('begin_date')
    context = {'event_list': dernier_event}
    return render(request, 'event/liste.html', context)

def profil(request):
    
    if request.user.is_authenticated:     
        eventList = request.user.events_set.all()
        nbTicketList = {}
        context = {'nbTicketList':nbTicketList}   
        for event in eventList:
            nbTicketList[event] = request.user.achat_set.get(event=event).billets_user
        return render(request, 'event/profil.html', context)
    else:
        return render(request, 'event/error_log.html' )
    
    

def acheter(request, event_id):
    if request.user.is_authenticated:
        event = Events.objects.get(pk=event_id)
        try:
            achat = Achat.objects.get(user = request.user, event = event)
        except Achat.DoesNotExist:
            achat = event.users.add(request.user)
        # except request.user == AnonymousUser:
        #     achat = event.users.add(request.user)
            print('ko')
        finally:
            achat = Achat.objects.get(event = event, user = request.user)
            achat.billets_user += 1
            event.av_ticket -=1
            event.save()
            achat.save()
            context = { 'event':event }
            return render(request, 'event/acheter.html', context)
    else:
        return render(request, 'event/error_log.html' )

def annuler(request,event_id):
    event = Events.objects.get(pk=event_id)
    achat = Achat.objects.get(event = event, user = request.user)
    achat.billets_user -= 1
    achat.save()
    if achat.billets_user == 0:
        achat.delete()
    event.av_ticket +=1
    event.save()
    context = { 'event':event }
    return render(request, 'event/annuler.html', context)

def salle(request):
    return render(request, 'event/salle.html')

TiersMonde/event/templates/event/acheter.html
{% extends 'event/index.html' %}
{% load static %}

{% block contenue %}
<h1 class="title4">Félicitation</h1>
{% for group in event.group.all %}
<h1 class="p_detail">Votre commande a bien été pris en compte par notre site de réservation.</h1>
<p class="p_detail">Le <strong>{{ event.begin_date }}</strong> se tiendra le <strong>{{ event.type }} {{ event.name_event }} avec {{ group.name_group }}</strong>
  <br>
  - L'acheteur est responsable de l'utilisation du billet
  <br>
  - Seule la première personne se présentant avec le billet sera admise à l'évènement.
</p>
{% endfor %}
<div class="boutonIndex">
    <a class="fancy-btn" href="{% url 'event:index' %}">Accueil</a>
    <a class="fancy-btn" href="{% url 'event:profil' %}">Profil</a>
</div>
{% endblock %}

TiersMonde/event/templates/event/annuler.html
{% extends "event/index.html" %}
{% load static %}

{% block contenue %}
<div class="containerInfo">
    <h1 class="title4">Annulation bien prise en compte!</h1>
    <a class="fancy-btn" href="{% url 'event:index' %}">Page d'accueil</a>
</div>
{% endblock %}

TiersMonde/event/templates/event/error_log.html
{% extends 'event/index.html' %}
{% load static %}
{% block contenue %}
<div class="containerInfo">
    <h1 class="title4">Vous devez être connecté</h1>
    <a class="fancy-btn" href="{% url 'event:index' %}">Revenir sur l'accueil</a>
</div>
{% endblock  %}

TiersMonde/event/templates/event/index.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'event/style.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css" /><!--Wrapper -->
    <script src="https://kit.fontawesome.com/8e8d5e63b3.js"></script><!--Icone -->
    <title>Accueil</title>
</head>

<body>
    <div class="header_container">
        <img class="logo" src="{% static 'event/images/logo_tiers_monde.png' %}">
        <nav>
            <div class="left">
                <ul>
                    <li><a href="{% url 'event:index' %}">Accueil</a></li>
                    <li><a href="{% url 'event:liste' %}">évènements</a></li>
                    <li><a href="{% url 'event:salle' %}">Salles</a></li>
                    <li><a href="{% url 'event:informations' %}">Informations</a></li>
                </ul>
            </div>
            <div class="right">
                <ul>
                    {% if not request.user.is_authenticated %}
                        <li><a href="{% url 'event:login' %}">Connexion</a></li>
                        <li><a href="{% url 'event:register' %}">Inscription</a></li>
                    {% else %}
                        <li><a href="{% url 'event:profil' %}">Profil</a></li>
                        <li><a href="{% url 'event:logout' %}">Déconnexion</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>

    {% block contenue %}
        <div class="title_container">
            <h1>Zenith du Tiers Monde</h1>
            <p>Adrar Project by San Gokool, A©e, Mojo-Jojo and Kheandee.</p>
            <div class="boutonIndex">
                <a href="#programmation" class="fancy-btn">Programmation</a><br>
            </div>
        </div>

        <div id="stripped">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1500 1062">
                <polyline points="0,154 131,0 0,348 269,0 0,562 437,0 
                0,766 565,14 0,1062 719,0 289,1062 843,0 543,1062 995,0 729,1062 1161,0 947,1062 1307,0 1143,1062 1500,162 1299,1062 1500,830"/>
            </svg>
        </div>

<!-- --------------------SLIDER --------------------------->
<h2 class="title2">Nouveautés</h2>
<div class="swiper">
    <div class="swiper-wrapper">
                    {% for event in event_list %}
                        {% for group in event.group.all %}
                        <div class="swiper-slide">
                            <div class="slider-box">
                                {% if group.pics_group %}
                                <img class="img_slider" src="{{ group.pics_group.url }}">
                                {% endif %}
                            </div>
                            <div class="text_slider stripped2">                            
                                <h2 class="title3">{{ event.name_event }}</h2>
                                <h2 class="title3">{{ event.av_ticket }} places disponible</h2>
                                {% language 'fr' %}
                                <h2 class="title3">{{ event.begin_date|date:'d F Y' }}</h2>
                                {% endlanguage %}
                            </div>
                        </div>
                        {% endfor %}
                    {% endfor %}
        </div><!--fin du swiper wrapper -->   
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
        <div class="swiper-scrollbar"></div>
    </div><!--fin du swiper contenaire -->

<!-- --------------------PROGRAMMATION --------------------------->
    {% if event_list %}
        <h2 id="programmation" class="title2">Programmation</h2>
        <ul class="prog">
            {% for event in event_list %}
            <li>
            <div class="content-wrapper">
                <div class="news-card">
                {% for group in event.group.all %}
                {% if group.pics_group %}
                <img class="news-card__image" src="{{ group.pics_group.url }}"><br>
                {% endif %}
                {% endfor %}
                <div class="news-card__text-wrapper">
                    <h3 class="news-card__title">{{ event.name_event }}</h3><br>
                    {% language 'fr' %}
                    <div class="news-card__post-date">Du {{ event.begin_date|date:'d F Y' }} au {{ event.end_date|date:'d F Y' }}</div><br>
                    {% endlanguage %}
                    <div class="news-card__details-wrapper">
                        <p class="news-card__excerpt">{{ event.description_event }}&hellip;</p>
                        <div class="boutonIndex">
                            <a href="{% url 'event:detail' event.id %}" class="fancy-btn">Informations/Réservations</a><br>
                        </div>     
                    </div>
                </div>
                </div>
            </div>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Pas d'évènements disponible</p>
    {% endif %}

    <!-- --------------------QUOTE --------------------------->
    <h2 class="title2">Avis</h2>
    <div class="blockquote-wrapper">
        <div class="blockquote">
            <h1>
                Aussi bon qu'un<span style="color:#ffffff"> Balisto !</span>
            </h1>
            <h4>&mdash;Maxime Pryzbylo<br><em>Critique de renommée international</em></h4>
        </div>
        <div class="blockquote">
            <h1>
                Une organisation digne des meilleurs <span style="color:#ffffff"> MCD - MLD que je n'ai jamais connu !</span>
            </h1>
            <h4>&mdash;Florence Calmettes<br><em>Directrice régional du théatre Adrar</em></h4>
        </div>
        <div class="blockquote">
            <h1>
                Comme vous le savez <span style="color:#ffffff"> même en asynchrone, un show que je recommande absolument !</span>
            </h1>
            <h4>&mdash;Laurence Collot<br><em>Responsable artistique</em></h4>
        </div>
    </div>
    {% endblock %}

    <!-- Site footer -->
    <footer class="footer-distributed">
        <div class="footer-left">
            <img class="logo" src="{% static 'event/images/logo_tiers_monde.png' %}">
            <p class="footer-links">
                <a href="{% url 'event:index' %}" class="link-1">Accueil</a>
                <a href="{% url 'event:informations' %}">Informations</a>
                <a href="{% url 'event:login' %}">Connexion</a>
                <a href="{% url 'event:faq' %}">Faq</a>
                <a href="{% url 'event:contact' %}">Contact</a>
            </p>
            <p class="footer-company-name"> Adrar Formation TP© 2022</p>
        </div>
        <div class="footer-center">
            <h2 class="title_footer">Coordonnées</h2>
            <div>
                <i class="fa fa-map-marker"></i>
                <p><span>11 avenue de l'Europe</span> Ramonville, Toulouse</p>
            </div>
            <div>
                <i class="fa fa-phone"></i>
                <p>07 71 81 80 20</p>
            </div>
            <div>
                <i class="fa fa-envelope"></i>
                <p><a href="mailto:zenith_du_tiers_monde@gmail.com">zenith_du_tiers_monde@gmail.com</a></p>
            </div>
        </div>
        <div class="footer-right">
        <p class="footer-company-about">
            <h2 class="title_footer">A propos</h2>
            <p>Designed by Mojo_Jojo© / Powered by San Gokool©</p>
            <p>Sustained by Kheandee© and A©e</p>
            <p>Remerciements à Maxime Torlois pour sa participation</p>
        </p>
        <div class="footer-icons">
            <a href="https://fr-fr.facebook.com/lesoubliesdutiersmonde/"><i class="fa fa-facebook"></i></a>
            <a href="https://twitter.com/endatiersmonde"><i class="fa fa-twitter"></i></a>
            <a href="https://ch.linkedin.com/company/gen-ve-tiers-monde"><i class="fa fa-linkedin"></i></a>
            <a href="https://github.com/johan-valero/Zenith2.0.git"><i class="fa fa-github"></i></a>
        </div>
        </div>
    </footer>

    <script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
    <script src="{% static 'event/script.js' %}"></script>
</body>
</html>

TiersMonde/event/templates/event/informations.html
{% extends 'event/index.html' %}
{% load static %}

    {% block contenue %}
    <div class="containerInfo">
        <h1 class="title2">Informations</h1>
        <div id="stripped2">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1500 1062">
                <polyline points="0,154 131,0 0,348 269,0 0,562 437,0 
                0,766 565,14 0,1062 719,0 289,1062 843,0 543,1062 995,0 729,1062 1161,0 947,1062 1307,0 1143,1062 1500,162 1299,1062 1500,830"/>
            </svg>
        </div>

        <h1 class="title">Informations</h1>
        <h3 class="title2">Reports et annulations</h3>
        <div class="info_detail">
            <p class="p_detail">A la suite des mesures gouvernementales successives adoptées pour lutter contre la propagation du COVID-19, les événements prévus au Zénith du Tiers Monde depuis le mois de mars 2020 sont impactés. Nous vous invitons à consulter régulièrement cette page mise à jour en temps réel avec les dernières informations connues et transmises par les producteurs de spectacle.
            Les billets restent valables pour la date de report, sans aucune démarche à effectuer. Le placement indiqué sur le billet de la date initiale reste inchangé pour la date de report.
            Les personnes ne pouvant se rendre à l'événement reporté, sont invitées à s'adresser à leur point de vente pour effectuer une demande de remboursement conformément aux conditions générales de vente.
            Calendrier des dates reportées/annulées consultable par ICI
            A partir du 14 mars 2022, le Zénith du Tiers Monde n'est plus soumis au contrôle du pass sanitaire, et le port du masque n'est plus obligatoire.
            Du gel hydroalcolique est mis à disposition des spectateurs, que nous invitons à respecter les gestes barrières et règles d'hygiène.</p>
        </div>
            
        <h2 class="title2">Billetterie</h2>
        <div class="info_detail">
            <p class="p_detail">Le Zénith du Tiers Monde n'est pas point de vente billetterie. Le guichet du Zénith du Tiers Monde n'est ouvert que certains soirs de spectacle et tenu par les Producteurs détenteurs de leur billetterie. Le guichet se situe sur l'aile gauche du Zénith du Tiers Monde.
            Il convient d’être très vigilant sur les conditions d'achat des billets. Sur chaque fiche spectacle de notre site internet, il vous est proposé de réserver en ligne avec notre partenaire Ticketmaster ou avec les organisateurs de spectacle qui proposent leur propre billetterie et qui gèrent la plateforme PMR. ATTENTION aux sites frauduleux qui revendent des billets à des prix exorbitants (au-delà de leur vraie valeur), des billets contrefaits, ou même des duplicatas du même billet revendus plusieurs fois. Pour la majorité des spectacles, vous pouvez également trouver des billets dans les points de ventes habituels : Auchan, Carrefour, Cultura, E.Leclerc, Fnac…
            Billet EARLY ACCESS : Placement en fosse debout, accès 30 minutes avant l’ouverture des portes, priorité non garantie au-delà.
            En cas d'annulation ou de report de la manifestation, les modalités de remboursement du billet seront définies par l'organisateur / producteur de l'évènement. Le Zénith du Tiers Monde ne peut en aucun cas être tenu pour responsable du remboursement du billet, qui reste à la charge de l'organisateur de la manifestation.
            Les billets gagnés par jeux concours via les médias (radio, presse, etc.) sont à retirer au guichet billetterie du Zénith du Tiers Monde le jour de la manifestation (à partir d'1h30 avant le début du spectacle), sur présentation d'une carte d'identité.
            Les billets achetés sur le site Groupon ainsi que via l'appli Pass Culture, sont à retirer au guichet le jour de la manifestation (ouvert dès l'ouverture des portes 1h30 avant le début du spectacle) en échange du bon Groupon / du mail de confirmation et d'une pièce d'identité.</p>
        </div>
            
        <h2 class="title2">A l'intérieur du Zénith du Tiers Monde </h2>
        <div class="info_detail">
            <p class="p_detail">Ne peuvent entrer au Zénith du Tiers Monde que les personnes munies d’un billet ou d’une invitation valable pour une représentation donnée.
            Toute sortie est définitive.
            Aucun distributeur ne permet le retrait d’argent liquide à l’intérieur du Zénith du Tiers Monde.
            Bars et restauration rapide : plusieurs bars sont à disposition du public et proposent boissons fraiches, cafés, sandwichs, hot-dog… De plus, Pik'n'Mix propose un choix de bonbons et des gaufres. 
            Il n’existe pas de consigne ni de vestiaire à l’intérieur du Zénith du Tiers Monde. A l’exception des casques de motocyclistes, qui sont conservés en consigne dès l’entrée sur site, et restitués à leur propriétaire à la fin du spectacle.
            Tout appareil photo est interdit dans l'enceinte du Zénith du Tiers Monde.</p>
        </div>
            
        <h2 class="title2">Contrôle de sécurité</h2>
        <div class="info_detail">
            <p class="p_detail">Dans le cadre de l'activation du Plan Vigipirate, la vérification du contenu des sacs est systématique et obligatoire à l'entrée du site.
            Il est interdit d'entrer au Zénith du Tiers Monde avec des appareils photos, d'enregistrement sonore et/ou audiovisuel. Pour des raisons de sécurité, il est formellement interdit d'introduire dans le site, des armes, substances explosives, des bouteilles en verre (seules les bouteilles en plastique de 50 cl maximum sans bouchon sont autorisées) et, d'une manière générale, tout objet susceptible de servir de projectile. Il est également interdit d'introduire, dans le site, tout objet dangereux et tout article pyrotechnique, des signes et banderoles de toute taille de nature politique, idéologique, religieuse ou publicitaire. Les objets interdits (non dangereux) pourront être mis en consigne. Les sacs à dos de plus de 10L sont interdits.
            Les gourdes et les casques sont consignés.</p>
        </div>
            
        <h2 class="title2">Règlement intérieur et objets perdus</h2>
        <div class="info_detail">
            <p class="p_detail">Le public est soumis à un règlement intérieur qui précise ses droits et devoirs dès lors qu’il pénètre dans l’enceinte du Zénith du Tiers Monde. Ce document est consultable et téléchargeable ici.
            Selon les termes du décret n° 2006-1386, il est rigoureusement interdit de fumer dans l’enceinte du Zénith du Tiers Monde. Un espace extérieur communiquant avec le hall est toutefois mis à la disposition des fumeurs.
            Objets perdus : merci de nous le signaler à contact@zenith-tm.com en indiquant la nature de l’objet et la date de la manifestation.</p>
        </div>
    
        <a class="fancy-btn" href="{% url 'event:index' %}">Accueil</a>
    </div>
    {% endblock %}

TiersMonde/event/templates/event/login.html
{% extends 'event/index.html' %}
{% load static %}
{% block contenue %}

    <div class="container_login">
        <div class="card_login">
            <div class="card-image">
                <h1 class="card-heading title2">Identifiez-vous</h1>
            </div>
            <a class="a_detail" href="{% url 'event:register' %}">Pas de compte ? Inscrivez-vous !</a>
            <form class="card-form" id="login" method="post" action="{% url 'event:welcome' %}">
                {% csrf_token %}
                <div class="input_login">
                    <input type="text" class="input-field" id="username" name="username" required />
                    <label class="input-label">Pseudo</label>
                </div>
                <div class="input_login">
                    <input type="password" class="input-field" id="password" name="password" required />
                    <label class="input-label">Mot de passe</label>
                </div>
                <div class="action_login">  
                    <input class="bouton_login" type="submit" value="Connexion">
                    <input type="hidden" name="{{next}}">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

TiersMonde/event/templates/event/logout.html
{% extends 'event/index.html' %}
{% load static %}

    {% block contenue %}
    <div class="containerInfo">
        <h3 class="title4">Merci de votre visite, à bientôt</h3>
        <a class="fancy-btn" href="{% url 'event:index' %}">Accueil</a>
    </div>
    {% endblock %}

TiersMonde/event/templates/event/profil.html
{% extends "event/index.html" %}
{% load static %}
{% load i18n %}

{% block contenue %}
    <h1 class="title2">Compte de {{request.user.username}} </h1>
    <div class="containerInfo">
        <div class="info_detail">
            <p class="p_detail">PSEUDO</p>
            <p class="p_detail">{{request.user.username}}</p>
            <div id="traitBas"></div>
            <p class="p_detail">PRENOM
            <p class="p_detail">{{request.user.last_name}}</p>
            <div id="traitBas"></div>
            <p class="p_detail">NOM
            <p class="p_detail">{{request.user.first_name}}</p>
        </div>
    </div>

    <h3 class="title4">Vos billets</h3>
    {% for event_list, nb_ticket in nbTicketList.items %}
    <div class="containerBillet">
        <div class="fancy-btn">
            <h2>{{event_list.name_event}}</h2>
            {% for group in event_list.group.all %}
                <h2>{{group.name_group}}</h2>
            {% endfor %}
            {% language 'fr' %}
                <h2>{{event_list.begin_date}}</h2>
            {% endlanguage %}
            {{nb_ticket}} places
        </div>
    <div class="bouton_billets">
        <a href="{% url 'event:detail' event_list.id %}"><input class="bouton_login" type="submit" value="Détails"></a>
        <a href="{% url 'event:annuler' event_list.id %}"><input class="bouton_login" type="submit" value="Annuler"></a>
    </div>
    </div>
    {% endfor %}
{% endblock %}

TiersMonde/event/templates/event/register.html
{% extends "event/index.html" %}
{% load static %}
{% block contenue %}

<div class="container_login">
    <div class="card_login">
        <div class="card-image">
            <h1 class="card-heading title2">Inscription</h1>
        </div>
        <a class="a_detail" href="{% url 'event:login' %}">Déjà un compte ? Connectez-vous !</a>
        <form class="card-form" id="register" method="post" action="{% url 'event:registered' %}">
            {% csrf_token %}
            <div class="input_login">
                <input type="text" class="input-field" id="user_name" name="user_name" required/>
                <label class="input-label" for="user_name">Nom</label>
            </div>
            <div class="input_login">
                <input type="text" class="input-field" id="user_firstname" name="user_firstname" required/>
                <label class="input-label" for="user_firstname">Prénom</label>
            </div>
            <div class="input_login">
                <input type="text" class="input-field" id="user_email" name="user_email" required/>
                <label class="input-label" for="user_email">Email</label>
            </div>
            <div class="input_login">
                <input type="password" class="input-field" id="user_pwd" name="user_pwd" required/>
                <label class="input-label" for="user_pwd">Mot de passe</label>
            </div>
            <div class="action_login">
                <input class="bouton_login" type="submit" value="Enregistrer">
            </div>
        </form>
    </div>
</div>
{% endblock %}

TiersMonde/event/templates/event/registered.html
{% extends 'event/index.html' %}
{% load static %}

    {% block contenue %}
    <div class="containerInfo">
        <h1 class="title4">Bienvenue</h1>
        <p class="p_detail">
            Votre nom d'utilisateur est : {{user.username}}
        </p>
        <a class="fancy-btn" href="{% url 'event:login' %}">Login</a>
    </div>
    {% endblock %}

TiersMonde/event/templates/event/reserver.html
{% extends "reservation/index.html" %}
{% load static %}


{% block content%}
    <div class="containerInfo">
        <h1 class="title4">réservation prise en compte !</h1>
        <a class="fancy-btn" href="{% url 'event:index' %}">Page d'accueil</a>
    </div>
{% endblock %}

TiersMonde/event/templates/event/welcome.html
{% extends "event/index.html" %}
{% load static %}
{% block contenue %}

<div class="containerInfo">
    <h1 class="title4">Bienvenue {{user.last_name}} {{user.first_name}}!</h1>
    <p class="p_detail">Connexion réussi !</p>
    <a class="fancy-btn" href="{% url 'event:index' %}">Page d'accueil</a>
</div>

{% endblock %}